<br>

#### 6. 클래스

In [ ]:
#1. snake-case, snake-pattern -> random_func, num_list
#2. camel-case, camel-pattern -> AnimalCage, AddMinus

class AniCage:
    pass

In [7]:
class Box:
    pass

In [8]:
class Cage(Box): # class의 상속(inheritance)    
    pass

In [ ]:
def function(x,y): # parameter 매개변수
    pass
function(2,3) # argument 인자

In [28]:
class Cage: # 클래스 X를 상속할 때에는 : class Cage(X):
    
    def print_something():
        print("This is something!")

In [29]:
cage_1 = Cage()

In [32]:
# Cage.print_something(cage_1) == cage_1.print_something()
Cage.print_something()

This is something!


In [31]:
cage_1.print_something()

TypeError: print_something() takes 0 positional arguments but 1 was given

In [33]:
class Cage:
    
    # 클래스 선언 후 객체가 메소드를 호출할 때 메소드를 호출한 객체 자신이 첫번째 인자로 함께 전달된다. 
    def print_something(self):
        print("This is something!")

In [34]:
cage_1 = Cage()

In [35]:
cage_1.print_something() # 메소드 호출, check_animals 메소드를 호출한 객체 cage_1 이 자동으로 self에 전달된다.

This is something!


In [57]:
class Cage:
    def __init__(self):
        self.defualt_cage=['Dog','Cat','Tiger']
    def print_something(self):
        print(self.defualt_cage)

In [58]:
cage_1=Cage()
cage_1.print_something()

['Dog', 'Cat', 'Tiger']


In [50]:
# 클래스를 따라 객체변수를 만들 때 처음부터 데이터가 담겨있기를 원한다면?

class Cage:
    
    # 생성자(Constructor), 클래스라는 설계도를 따라 객체를 만들 때 초기화값
    def __init__(self):
        self.animals = ['Cat', 'Dog', 'Tiger']
    
    def check_animals(self):
        print(self.animals) # self 키워드를 통해 함수의 scope를 뛰어넘어 접근이 가능합니다.

In [ ]:

model = sklearn.linear_model_LinearRegression()
df = pandas.DataFrame()


In [51]:
cage_1 = Cage() # 생성자 호출
cage_1

In [52]:
cage_1.check_animals() 

['Cat', 'Dog', 'Tiger']


In [44]:
p='Python'
print(type(p))

<class 'str'>


'Python'

In [49]:
print(p + ' is easy')
print(p.__add__(' is easy'))

Python is easy
Python is easy


In [40]:
class Cage:
    
    def __init__(self): # 생성자
        self.animals = ['Cat', 'Dog', 'Tiger']

    def check_animals(self):
        print(self.animals)
        
    def plus_animal(self, animal):
        self.animals.append(animal) # 리스트에 item 추가하기?
        print(self.animals)

In [41]:
cage_2 = Cage()
cage_2

In [140]:
cage_2.plus_animal('Pig')

['Cat', 'Dog', 'Tiger', 'Pig']


In [141]:
class Cage:
    
    def __init__(self, name='SampleCage'):
        self.instance_name = name
        self.animals = ['Cat', 'Dog', 'Tiger'] 
    
    def check_animals(self):
        print(self.animals)
        
    def plus_animal(self, animal):
        self.animals.append(animal) 
        print(self.animals)
        
    def __str__(self):
        return self.instance_name

In [142]:
cage_1 = Cage('FirstCage') 
print(cage_1)

FirstCage


#### Pass (why we need 'self')

In [143]:
Cage.check_animals(cage_1) # == cage1.check_animals() -> cage_1 객체를 check_animals()에게 인자로 던져주는 것

['Cat', 'Dog', 'Tiger']


In [144]:
Cage.check_animals(cage_2) # == cage2.check_animals()

['Cat', 'Dog', 'Tiger', 'Pig']


In [145]:
# 사실 cage_1.check_animals()를 실행하면 
# 백그라운드에서는 Cage.check_animals(chech_1) 이 실행되는 것
# 이 때 클래스 Cage 가 어떤 객체(instance)의 메소드를 호출해야하는지 모르기 때문에 객체를 인자로 전달해줘야 한다.

<br>

#### 7. Python 기본 내장함수와 외장함수

In [22]:
len('Python') # 길이?

6

In [28]:
list('Python')
p='Python'

In [1]:
dir('Python') # (여기서는 string) 객체가 자체적으로 가지고 있는 변수나 함수
# "Python"은 'str'이라는 데이터타입(클래스)이 만들어낸 객체이며 
# 'str' 데이터타입(클래스)에 정의된 모든 속성(객체변수)과 메소드를 상속 받음

In [33]:
from sklearn import linear_model

for name_space in dir(linear_model):
    if 'CV' in name_space:
        print(name_space)

ElasticNetCV
LarsCV
LassoCV
LassoLarsCV
LogisticRegressionCV
MultiTaskElasticNetCV
MultiTaskLassoCV
OrthogonalMatchingPursuitCV
RidgeCV
RidgeClassifierCV


In [150]:
abs(-1.2) # '절대값'의 앞 3글자

1.2

In [151]:
round(1.7) # 반올림

2

In [152]:
bool(1) # 참/거짓 판별
# 0 - False 
# except 0 - True

True

In [153]:
sum([1, 2, 3]) # 합

6

In [154]:
max([1, 2, 3]) # 최대값

3

In [155]:
min([1, 2, 3]) # 최소값

1

In [35]:
import numpy as np
print(np.sum([1,2,3]),np.max([1,2,3]),np.min([1,2,3]))

6 3 1


In [156]:
def func(x):
    return x**2

In [157]:
func(5)

25

In [38]:
# x(input) 를 받아 x**2(output) 를 return 해주는 람다 함수
# anonymous function ? 익명 함수.
func_2= lambda x:x**2

In [39]:
func_2(5)

25

In [42]:
my_func= lambda x,y,z : x**2*y**0.5/(z+1.)

In [45]:
my_func(3.,2.,3.)

3.1819805153394642

In [ ]:
def check_price(price):
    if price > 25:
        return 'over'
    else:
        return 'under'

In [ ]:
check_price(50)


In [48]:
# 한 줄로 쓰는 if문, elif는 사용 불가. if와 else만 사용가능!
cp = lambda price: 'over' if price > 25 else 'under'

In [49]:
cp(20)

'under'

8.라이브러리 활용하기 (Library == Package, Module(단일 .py)의 상위 개념 )

Module 
Library == Package

In [40]:
# MAGIC METHOD
%%writefile module_example.py

# @ module_example.py

def print_something() : 
    print('Hello world!')

def sum_nums(num1, num2) : 
    result = num1 + num2
    return result

Writing module_example.py


In [57]:
# %ls module_example.py
import astropy

# pip install ~##
# conda install ~##

'\nAstropy is a package intended to contain core functionality and some\ncommon tools needed for performing astronomy and astrophysics research with\nPython. It also provides an index for other astronomy packages and tools for\nmanaging them.\n'

In [59]:
# Jupyter notebook 에서 pip 실행 방법

!pip install numpy

In [41]:
import module_example

module_example.print_something()

Hello world!


In [51]:
module_example.sum_nums(1,2)

3

In [52]:
import numpy # import 라이브러리이름

In [164]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [61]:
import numpy as np # import 라이브러리이름 as 별명

In [166]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [167]:
from numpy import array, ndarray # from 라이브러리이름 import 함수이름

In [168]:
a = array([1, 2, 3])
a

array([1, 2, 3])

In [63]:
import random # 외장함수

x = random.random()
x

0.3839748811910261

In [173]:
x = random.randint(1, 100) # 1과 100 사이의 '정수' 를 랜덤하게 뽑으려면? Shift + Tab 을 활용해보세요!
x

42

In [64]:
import os # 외장함수

os.getcwd() # get current working directory

'C:\\Users\\student\\python_DEC'

#### pip 명령어 살펴보기 : pip + [ list/freeze/check, show/install/uninstall library_name, search search_keyword ]

In [ ]:
# cmd 에서 입력해 결과를 확인해보세요.

pip list
pip freeze > lib_list.txt # 1
pip check

pip show numpy # 2
pip install numpy (주의 버전 확인) # 3
pip uninstall numpy (주의 버전 확인) # 4

pip search xgboost # 5

In [65]:
!pip freeze

absl-py==0.8.1
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-navigator==1.9.7
anaconda-project==0.8.2
asn1crypto==0.24.0
astor==0.8.0
astroid==2.2.5
astropy==3.1.2
atomicwrites==1.3.0
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
bitarray==0.8.3
bkcharts==0.2
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
Bottleneck==1.2.1
certifi==2019.11.28
cffi==1.12.2
chardet==3.0.4
Click==7.0
cloudpickle==0.8.0
clyent==1.2.2
colorama==0.4.1
comtypes==1.1.7
conda==4.7.12
conda-build==3.17.8
conda-package-handling==1.3.11
conda-verify==3.1.1
contextlib2==0.5.5
cryptography==2.6.1
cycler==0.10.0
Cython==0.29.6
cytoolz==0.9.0.1
dask==1.1.4
decorator==4.4.0
defusedxml==0.5.0
distributed==1.26.0
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.10
Flask==1.0.2
future==0.17.1
gast==0.3.2
gevent==1.4.0
glob2==0.6
greenlet==0.4.15
grpcio==1.16.1
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.8
