In [ ]:
from keras.models import load_model
model = load_model('face_detection_js.h5')

In [1]:
import cv2, os, copy
from sklearn.externals import joblib
import numpy as np

from keras.models import load_model

model = load_model('face_detection_js.h5')

da_count=0
ch_count=0
un_count=0

ii=0
jj=0
kk=0

frame_count = 0

cascade_file = "haarcascade_frontface.xml"
cascade = cv2.CascadeClassifier(cascade_file)

cap = cv2.VideoCapture("KnaivesOut.mp4")

while True:
    # 이미지 추출하기
    is_ok, frame = cap.read()
    
    frame = cv2.resize(frame, (1280//2, 720//2))
    
    if not is_ok: break
        
    frame2 = copy.copy(frame)
    frame_count += 1
    
    # 이전 프레임과 비교를 위해 흑백으로 변환하기 --- (*2)
    gray = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)
    face_list = cascade.detectMultiScale(gray)
    
    if len(face_list) == 0:
        quit()
         
    for (x,y,w,h) in face_list:
        roi = frame2[y:y+h, x:x+w]
        imagex = cv2.resize(roi, (150, 150))
        image_data = imagex.reshape(1, 150, 150,3 )
    
        color = (255, 0, 0)
    
        pred_y = model.predict(image_data) # --- (*4)
        print(pred_y)
        
        if np.argmax(pred_y) == 0:
                cv2.rectangle(frame2, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame2,'DanielCraig',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
                da_count+=1
                if da_count % 7 == 0:
                    fname =  "res/da/daniel" + str(ii) + ".jpg"
                    cv2.imwrite(fname, frame2)
                    ii+=1
                #count += 1
        elif np.argmax(pred_y) == 1:
                cv2.rectangle(frame2, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame2,'ChrisEvans',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
                ch_count+=1
                if ch_count % 7 == 0:
                    fname =  "res/ch/chris" + str(jj) + ".jpg"
                    cv2.imwrite(fname, frame2)
                    jj+=1
        else:
                cv2.rectangle(frame2, (x, y), (x+w, y+h), color, thickness=4)
                cv2.putText(frame2,'Unknown',(x,y-20),cv2.FONT_ITALIC, 0.5, (255,255,255))  
                un_count+=1
                if un_count % 7 ==0:
                    fname =  "res/un/unkn" + str(kk) + ".jpg"
                    cv2.imwrite(fname, frame2)       
                    kk+=1
            
    #cv2.imshow('W', frame2)
    if cv2.waitKey(1) == 13: break  
    
cap.release()
cv2.destroyAllWindows()

#print("ok", count, "/", frame_count)

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 1.0380726e-36 0.0000000e+00]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 0. 1.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[1.0000000e+00 1.4773844e-09 1.5898013e-35]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 5.978299e-29]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[0.

KeyboardInterrupt: 